10 JUNE 2026 WEDNESDAY

In [45]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in /Users/ramakanthvprabhu/Desktop/PG_S3/.venv/lib/python3.14/site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in /Users/ramakanthvprabhu/Desktop/PG_S3/.venv/lib/python3.14/site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in /Users/ramakanthvprabhu/Desktop/PG_S3/.venv/lib/python3.14/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in /Users/ramakanthvprabhu/Desktop/PG_S3/.venv/lib/python3.14/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in /Users/ramakanthvprabhu/Desktop/PG_S3/.venv/lib/python3.14/site-packages (from scikit-learn) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in /Users/ramakanthvprabhu/Desktop/PG_S3/.venv/lib/python3.14/site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

Label Encoding

In [46]:
from sklearn.preprocessing import LabelEncoder

In [47]:
data = ['Red', 'Blue', 'Green', 'Blue']

In [48]:
le = LabelEncoder()
encoded_data = le.fit_transform(data)
print('Encoded Data:\n', encoded_data)

Encoded Data:
 [2 0 1 0]

One-Hot Encoding

In [49]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

In [50]:
data = pd.DataFrame({'Fruits': ['Apple', 'Mango', 'Banana', 'Mango', 'Orange', 'Apple']}, columns = ['Fruits'])

In [51]:
data

   Fruits
0   Apple
1   Mango
2  Banana
3   Mango
4  Orange
5   Apple

In [52]:
one_hot_encoded = pd.get_dummies(data['Fruits'])

In [53]:
one_hot_encoded

   Apple  Banana  Mango  Orange
0   True   False  False   False
1  False   False   True   False
2  False    True  False   False
3  False   False   True   False
4  False   False  False    True
5   True   False  False   False

Ordinal Encoding

In [54]:
from sklearn.preprocessing import OrdinalEncoder

In [55]:
data = {'Grade':['High', 'Medium', 'Low', 'High']}
df = pd.DataFrame(data)
print(df)

    Grade
0    High
1  Medium
2     Low
3    High

In [56]:
encoder_ord = OrdinalEncoder(categories = [['Low', 'Medium', 'High']]) # Use [[]]
encoded_data = encoder_ord.fit_transform(df[['Grade']])
print(encoded_data)

[[2.]
 [1.]
 [0.]
 [2.]]

In [57]:
type(encoded_data)

numpy.ndarray

In [58]:
for i in encoded_data:
  if i == [0.]:
    print(i, 'Low')
  elif i ==[1.]:
    print(i, 'Medium')
  else:
    print(i, 'High')

[2.] High
[1.] Medium
[0.] Low
[2.] High

Target Encoding

In [59]:
import category_encoders as ce

In [60]:
df = pd.DataFrame(
    {'City': ['London', 'Paris', 'London', 'Berlin'], 
     'Target': [1, 0, 1, 0]}
)

In [61]:
encoder_target = ce.TargetEncoder(cols = ['City'])
df_tgt = encoder_target.fit_transform(df['City'], df['Target'])
df_tgt

       City
0  0.570926
1  0.434946
2  0.570926
3  0.434946

Binary Encoder

In [62]:
import category_encoders as ce

In [64]:
data_bin = ['Red', 'Green', 'Blue', 'Red']
encoder_bin = ce.BinaryEncoder(cols = ['Color'])
encoder_data = encoder_bin.fit_transform(pd.DataFrame(data_bin, columns = ['Color']))
encoder_data

   Color_0  Color_1
0        0        1
1        1        0
2        1        1
3        0        1