10 JUNE 2026 WEDNESDAY

In [ ]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

Label Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
data = ['Red', 'Blue', 'Green', 'Blue']

In [ ]:
le = LabelEncoder()
encoded_data = le.fit_transform(data)
print('Encoded Data:\n', encoded_data)

Encoded Data:
 [2 0 1 0]

One-Hot Encoding

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

In [ ]:
data = pd.DataFrame({'Fruits': ['Apple', 'Mango', 'Banana', 'Mango', 'Orange', 'Apple']}, columns = ['Fruits'])

In [ ]:
data

   Fruits
0   Apple
1   Mango
2  Banana
3   Mango
4  Orange
5   Apple

In [ ]:
one_hot_encoded = pd.get_dummies(data['Fruits'])

In [ ]:
one_hot_encoded

   Apple  Banana  Mango  Orange
0   True   False  False   False
1  False   False   True   False
2  False    True  False   False
3  False   False   True   False
4  False   False  False    True
5   True   False  False   False

Ordinal Encoding

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
data = {'Grade':['High', 'Medium', 'Low', 'High']}
df = pd.DataFrame(data)
print(df)

    Grade
0    High
1  Medium
2     Low
3    High

In [ ]:
encoder_ord = OrdinalEncoder(categories = [['Low', 'Medium', 'High']]) # Use [[]]
encoded_data = encoder_ord.fit_transform(df[['Grade']])
print(encoded_data)

[[2.]
 [1.]
 [0.]
 [2.]]

In [ ]:
type(encoded_data)

numpy.ndarray

In [41]:
for i in encoded_data:
  if i == [0.]:
    print(i, 'Low')
  elif i ==[1.]:
    print(i, 'Medium')
  else:
    print(i, 'High')

[2.] High
[1.] Medium
[0.] Low
[2.] High