# n-grams

06 July 2026, Monday

In [2]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
text = "This is a sample text for generating n-grams."

### strict bigram

In [13]:
vectorizer_22 = CountVectorizer(ngram_range=(2, 2))

In [14]:
X = vectorizer_22.fit_transform([text])

In [16]:
df = pd.DataFrame(X.toarray(), columns = vectorizer_22.get_feature_names_out())
df

   for generating  generating grams  is sample  sample text  text for  this is
0               1                 1          1            1         1        1

### Combination of Unigram and Bigram

In [17]:
vectorizer_12 = CountVectorizer(ngram_range=(1, 2))

### Use (𝑚𝑖𝑛_𝑛≤𝑚𝑎𝑥_𝑛)

In [18]:
X_12 = vectorizer_12.fit_transform([text])

In [20]:
df_12 = pd.DataFrame(X_12.toarray(), columns = vectorizer_12.get_feature_names_out())
df_12

,for,for generating,generating,generating grams,grams,is,is sample,sample,sample text,text,text for,this,this is
0,1,1,1,1,1,1,1,1,1,1,1,1,1